baseURL = ""
languageCode = "en-us"
title = "Tickets Final"
theme = "hugo-ticket-theme"

[params]
    theme_color = "#574CDD"
    description = "Tickets Final"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"

[params.nav]
    enable = false

[params.tickets]
    enable = true

[params.header]
    enable = false

[params.footer]
    enable = false
